### ISSUE TITLE
Some characters are HTML encoded

### ISSUE THREAD

**Issue by scholtzm** [linuxenko/lessmd#4]
Some characters are being HTML encoded which seems pretty unneccesary.

Example with `'`:

<img width="256" alt="screen shot 2016-11-14 at 19 20 55" src="https://cloud.githubusercontent.com/assets/2640934/20277149/a5e5c3e2-aa9f-11e6-9b2a-b7e4644a99ba.png">

**Comment by linuxenko** [comment]
you are right, it finally fixed in `1.1.0`

**Comment by scholtzm** [comment]
`v1.1.0` works as expected, thanks.
